const http=require('http');
const WebSocket=require('ws');
const PORT=process.env.PORT||3000;
const rooms=new Map();
const send=(ws,x)=>ws.readyState===1&&ws.send(JSON.stringify(x));
const code=()=>{let c;do{c=Math.random().toString(36).slice(2,6).toUpperCase()}while(rooms.has(c));return c};
function state(r){return {type:'state',code:r.code,players:r.players.map(p=>({id:p.id,name:p.name,money:p.money,admin:p.admin,active:p.active})),messages:r.messages}}
function broadcast(r){r.players.forEach(p=>send(p.ws,state(r)))}
function dice(){return Array.from({length:5},()=>1+Math.floor(Math.random()*6))}
const html=`<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dobbelen 11/24</title><style>*{box-sizing:border-box}body{margin:0;background:#075b3b;color:#fff;font:18px Arial;text-align:center}.wrap{max-width:650px;margin:auto;padding:20px}h1{font-size:40px}.card{background:#06452d;border:3px solid #d4af37;border-radius:22px;padding:22px;margin:18px 0}input{width:90%;max-width:400px;padding:15px;margin:7px;border:0;border-radius:12px;font-size:18px}button{background:#d4af37;border:0;border-radius:12px;padding:15px 22px;margin:7px;font-size:18px;font-weight:bold}.hidden{display:none}.code{font-size:44px;font-weight:bold;letter-spacing:8px}.player{background:#0b7049;padding:12px;border-radius:10px;margin:7px}.dice{font-size:58px;margin:18px}.chat{height:150px;overflow:auto;background:#033a25;border-radius:10px;text-align:left;padding:10px}.status{margin:10px;opacity:.85}</style></head><body><div class="wrap"><h1>🎲 Dobbelen 11/24</h1><section id="login" class="card"><h2>Online spelen</h2><input id="name" placeholder="Je naam"><br><button id="new">🎟️ NIEUW SPEL</button><br><input id="room" placeholder="Spelcode" maxlength="4"><br><button id="join">➡️ DEELNEMEN</button><div id="status" class="status"></div></section><section id="game" class="hidden"><div class="card"><h2>🎟️ Spelcode</h2><div id="code" class="code">----</div></div><div class="card"><h2>👥 Spelers</h2><div id="players"></div></div><div class="card"><h2>🎲 Dobbelen</h2><div id="dice" class="dice">🎲 🎲 🎲 🎲 🎲</div><button id="roll">BEGIN WORP</button><div id="result" class="status"></div></div><div class="card"><h2>💬 Chat</h2><div id="chat" class="chat"></div><input id="msg" placeholder="Bericht"><button id="send">VERSTUUR</button></div></section></div><script>
let ws;
const $=id=>document.getElementById(id);
function connect(action,data){$('status').textContent='Verbinden...';ws=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host);ws.onopen=()=>ws.send(JSON.stringify({action,...data}));ws.onerror=()=>$('status').textContent='Verbinding mislukt.';ws.onmessage=e=>{const d=JSON.parse(e.data);if(d.type==='joined'){$('login').classList.add('hidden');$('game').classList.remove('hidden');$('code').textContent=d.code;$('status').textContent=''}if(d.type==='state'){ $('code').textContent=d.code;$('players').innerHTML=d.players.map(p=>'<div class="player">'+(p.admin?'👑 ':'')+p.name+' — €'+Number(p.money).toFixed(2)+' '+(p.active?'🟢':'⏸️')+'</div>').join('');$('chat').innerHTML=d.messages.join('<br>');$('chat').scrollTop=$('chat').scrollHeight}if(d.type==='roll'){const s=['','⚀','⚁','⚂','⚃','⚄','⚅'];$('dice').textContent=d.dice.map(x=>s[x]).join(' ');$('result').textContent='Totaal: '+d.dice.reduce((a,b)=>a+b,0)}if(d.type==='error')alert(d.message)}}
$('new').onclick=()=>{const name=$('name').value.trim();if(!name)return alert('Vul je naam in.');connect('create',{name})};
$('join').onclick=()=>{const name=$('name').value.trim(),room=$('room').value.trim().toUpperCase();if(!name)return alert('Vul je naam in.');if(!room)return alert('Vul een spelcode in.');connect('join',{name,code:room})};
$('roll').onclick=()=>ws&&ws.readyState===1&&ws.send(JSON.stringify({action:'roll'}));
$('send').onclick=()=>{const text=$('msg').value.trim();if(text&&ws&&ws.readyState===1){ws.send(JSON.stringify({action:'chat',text}));$('msg').value=''}};
</script></body></html>`;
const server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(html)});
const wss=new WebSocket.Server({server});
wss.on('connection',ws=>{ws.on('message',raw=>{let d;try{d=JSON.parse(raw)}catch{return}if(d.action==='create'){const r={code:code(),players:[],messages:[]};rooms.set(r.code,r);const p={id:Math.random().toString(36).slice(2),name:String(d.name).slice(0,30),money:100,admin:true,active:true,ws};r.players.push(p);ws.room=r;ws.player=p;send(ws,{type:'joined',id:p.id,code:r.code});broadcast(r);return}if(d.action==='join'){const r=rooms.get(String(d.code).toUpperCase());if(!r)return send(ws,{type:'error',message:'Spelcode bestaat niet.'});if(r.players.length>=4)return send(ws,{type:'error',message:'Dit spel zit vol.'});const p={id:Math.random().toString(36).slice(2),name:String(d.name).slice(0,30),money:100,admin:false,active:true,ws};r.players.push(p);ws.room=r;ws.player=p;send(ws,{type:'joined',id:p.id,code:r.code});broadcast(r);return}if(!ws.room)return;if(d.action==='roll'){const x=dice();ws.room.players.forEach(p=>send(p.ws,{type:'roll',dice:x}));return}if(d.action==='chat'){const t=String(d.text||'').slice(0,200).replace(/[<>]/g,'');ws.room.messages.push('<b>'+ws.player.name+':</b> '+t);if(ws.room.messages.length>50)ws.room.messages.shift();broadcast(ws.room)}});ws.on('close',()=>{if(ws.room&&ws.player){ws.player.active=false;broadcast(ws.room)}})});
server.listen(PORT,'0.0.0.0',()=>console.log('Dobbelen 11/24 draait op poort '+PORT));
